## Mini Project 2: Data cleaning in Python

#### Cleaning the dataset "Destination"

In [ ]:
#Import the pandas:
import pandas as pd

tourism_df = pd.read_csv("https://docs.google.com/spreadsheets/d/1TzjQeYev3wUgMjTB35EIhRcQIurMoUodoeZXKtGElLI/export?format=csv")
restaurants_df = pd.read_csv("https://docs.google.com/spreadsheets/d/1y7Wcrn3Goh1uGroy1bfL6r12lFW1JRJXAngiIZZ6Glk/export?format=csv")

In [ ]:
#Check the sample of data:
tourism_df.head(5)

,Destination,Region,Country,Category,Latitude,Longitude,Approximate Annual Tourists,Currency,Majority Religion,Famous Foods,Language,Best Time to Visit,Cost of Living,Safety,Cultural Significance,Description
0,Rome,Lazio,Italy,City,41.902.782,12.496.366,14 million,Euro,Roman Catholic,"Pizza, Pasta, Gelato",Italian,Spring (April-May) or Fall (Sept-Oct),Medium-high,"Generally safe, but watch out for pickpockets","The capital city, known for its historical lan...","A hub of ancient history and modern culture, w..."
1,Florence,Tuscany,Italy,City,43.769.581,11.255.772,10 million,Euro,Roman Catholic,"Pizza, Pasta, Gelato",Italian,Spring (April-May) or Fall (Sept-Oct),Medium-high,"Generally safe, but watch out for pickpockets","A Renaissance city famous for its art, archite...","Home to world-class museums, including the Uff..."
2,Venice,Veneto,Italy,City,45.435.559,12.336.196,10 million,Euro,Roman Catholic,"Pizza, Pasta, Gelato",Italian,Spring (April-May) or Fall (Sept-Oct),Medium-high,"Generally safe, but watch out for pickpockets","A unique city built on canals, known for its g...","An iconic city of water, renowned for romantic..."
3,Milan,Lombardy,Italy,City,45.464.643,918.854,7 million,Euro,Roman Catholic,"Risotto, Ossobuco, Panettone",Italian,Spring (April-May) or Fall (Sept-Oct),High,"Generally safe, but watch out for pickpockets","A fashion capital known for its shopping, muse...","A modern city with an ancient soul, featuring ..."
4,Naples,Campania,Italy,City,4.085.133,1.425.472,5 million,Euro,Roman Catholic,"Pizza, Pasta, Cannoli",Italian,Spring (April-May) or Fall (Sept-Oct),Medium,"Generally safe, but be aware of pickpockets","A vibrant city known for its delicious food, h...","Famous for pizza, Pompeii, and proximity to th..."

In [ ]:
#Check the data types:
tourism_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Destination                  209 non-null    object
 1   Region                       209 non-null    object
 2   Country                      209 non-null    object
 3   Category                     209 non-null    object
 4   Latitude                     209 non-null    object
 5   Longitude                    209 non-null    object
 6   Approximate Annual Tourists  209 non-null    object
 7   Currency                     209 non-null    object
 8   Majority Religion            209 non-null    object
 9   Famous Foods                 209 non-null    object
 10  Language                     209 non-null    object
 11  Best Time to Visit           209 non-null    object
 12  Cost of Living               209 non-null    object
 13  Safety                       209 non-null    object
 14  Cultural Significance        209 non-null    object
 15  Description                  159 non-null    object
dtypes: object(16)
memory usage: 26.3+ KB

In [ ]:
#Check and understand the data:
tourism_df.describe(include='all')

,Destination,Region,Country,Category,Latitude,Longitude,Approximate Annual Tourists,Currency,Majority Religion,Famous Foods,Language,Best Time to Visit,Cost of Living,Safety,Cultural Significance,Description
count,209,209,209,209,209,209,209,209,209,209,209,209,209,209,209,159
unique,208,138,21,49,182,184,35,12,10,66,27,14,6,9,208,159
top,Blue Lagoon,Monaco-Ville,Italy,City,45.437.078,7.426.435,1 million,Euro,Roman Catholic,"Fondue, R”sti, Raclette",German,Spring (April-May) or Fall (Sept-Oct),Medium-high,Generally safe,"National park known for glaciers, hiking trail...","A hub of ancient history and modern culture, w..."
freq,2,10,10,91,10,10,32,90,92,10,20,91,107,171,2,1

In [ ]:
#Check the null and missing values:
tourism_df.isna().sum()

Destination                     0
Region                          0
Country                         0
Category                        0
Latitude                        0
Longitude                       0
Approximate Annual Tourists     0
Currency                        0
Majority Religion               0
Famous Foods                    0
Language                        0
Best Time to Visit              0
Cost of Living                  0
Safety                          0
Cultural Significance           0
Description                    50
dtype: int64

In [ ]:
#Check the duplicates of all columns:
tourism_df[tourism_df.duplicated()]

Empty DataFrame
Columns: [Destination, Region, Country, Category, Latitude, Longitude, Approximate Annual Tourists, Currency, Majority Religion, Famous Foods, Language, Best Time to Visit, Cost of Living, Safety, Cultural Significance, Description]
Index: []

In [ ]:
#Clean the data replace the spaces by "_":
tourism_df.columns = tourism_df.columns.str.lower().str.replace(" ", "_")

In [ ]:
#Check the number of unique values in "cost_of_living" column:
tourism_df['cost_of_living'].nunique()

6

In [ ]:
#check the number of unique values in "destination" column:
tourism_df['destination'].nunique()

208

In [ ]:
#Rename the column "destination" to "city":
tourism_df = tourism_df.rename(columns={"destination": "city", "approximate_annual_tourists": "annual_tourists"})

In [ ]:
#Filter out destination categories that are not cities.
tourism_filtered = tourism_df[tourism_df['category'].isin(['City', 'Coastal City'])][['city', 'annual_tourists', 'cost_of_living']].reset_index()

In [ ]:
#Check the values in "annual_tourists" column:
tourism_filtered["annual_tourists"].head()

0    14 million
1    10 million
2    10 million
3     7 million
4     5 million
Name: annual_tourists, dtype: object

In [ ]:
# Replace some city names by the correcte ones:
tourism_filtered["city"] = tourism_filtered["city"].replace({
    "Ni?": "Niš",
    "Troms?": "Tromsø",
    "Helsing?r": "Helsingør",
    "M\xa0laga": "Málaga",
    "San Sebasti\xa0n": "San Sebastián",
    "Malm”": "Malmö"
})

In [ ]:
#A dictionary to attribute an id to each city:
city_dict = {'Aalborg': 1, 'Aarhus': 2, 'Akureyri': 3, 'Amsterdam': 4, 'Antalya': 5, 'Antwerp': 6, 'Athens': 7, 'Aveiro': 8, 'Barcelona': 9, 'Belgrade': 10, 'Bergen': 11, 'Berlin': 12, 'Bilbao': 13, 'Bordeaux': 14, 'Braga': 15, 'Bratislava': 16, 'Bregenz': 17, 'Bruges': 18, 'Brussels': 19, 'Budapest': 20, 'Cambridge': 21, 'Cannes': 22, 'Coimbra': 23, 'Cologne': 24, 'Copenhagen': 25, 'Dnipro': 26, 'Dresden': 27, 'Dublin': 28, 'Edinburgh': 29, 'Esch-sur-Alzette': 30, 'Florence': 31, 'Frankfurt': 32, 'Geneva': 33, 'Ghent': 34, 'Gothenburg': 35, 'Granada': 36, 'Graz': 37, 'Hamburg': 38, 'Heidelberg': 39, 'Helsingør': 40, 'Helsinki': 41, 'Innsbruck': 42, 'Istanbul': 43, 'Kazan': 44, 'Kharkiv': 45, 'Kiruna': 46, 'Krakow': 47, 'Kyiv': 48, 'Leuven': 49, 'Lisbon': 50, 'Liverpool': 51, 'Ljubljana': 52, 'London': 53, 'Lucerne': 54, 'Luxembourg': 55, 'Luxembourg City': 56, 'Lviv': 57, 'Lyon': 58, 'Madrid': 59, 'Malmö': 60, 'Manchester': 61, 'Marseille': 62, 'Mdina': 63, 'Milan': 64, 'Monaco-Ville': 65, 'Moscow': 66, 'Munich': 67, 'Málaga': 68, 'Nafplio': 69, 'Namur': 70, 'Naples': 71, 'Nice': 72, 'Niš': 73, 'Novi Sad': 74, 'Odense': 75, 'Odessa': 76, 'Oporto': 77, 'Oslo': 78, 'Ostend': 79, 'Paris': 80, 'Pisa': 81, 'Porto': 82, 'Prague': 83, 'Reykjavik': 84, 'Rome': 85, 'Roskilde': 86, 'Salzburg': 87, 'San Sebastián': 88, 'Seville': 89, 'Sochi': 90, 'St. Petersburg': 91, 'Stockholm': 92, 'Strasbourg': 93, 'Subotica': 94, 'Tromsø': 95, 'Uppsala': 96, 'Valencia': 97, 'Valletta': 98, 'Venice': 99, 'Verona': 100, 'Vienna': 101, 'Visby': 102, 'Vladivostok': 103, 'Warsaw': 104, 'Zurich': 105}

In [ ]:
#Associate each city with ad "id":
tourism_filtered["city_id"] = tourism_filtered["city"].map(city_dict)
tourism_filtered

    index      city annual_tourists cost_of_living  city_id
0       0      Rome      14 million    Medium-high       85
1       1  Florence      10 million    Medium-high       31
2       2    Venice      10 million    Medium-high       99
3       3     Milan       7 million           High       64
4       4    Naples       5 million         Medium       71
..    ...       ...             ...            ...      ...
89    194  Akureyri             200         Medium        3
90    199  Belgrade     1.5 million         Medium       10
91    200  Novi Sad             500         Medium       74
92    201       Niš             300         Medium       73
93    207  Subotica              20         Medium       94

[94 rows x 5 columns]

In [ ]:
#Function to convert the "annual_tourists" values to numeric format (ex. 12 million to 12,000,000):
def convert_tourists(value):
    value = str(value).strip()

    # Case 1: range in millions (e.g. 35-40 million)
    if "million" in value and "-" in value:
        low, high = value.replace(" million","").split("-")
        return int((float(low) + float(high)) / 2 * 1_000_000)

    # Case 2: single value in millions (e.g. 14 million)
    elif "million" in value:
        return int(float(value.replace(" million","")) * 1_000_000)

    # Case 3: already a number (thousands or hundreds)
    else:
        return int(float(value))

tourism_filtered["annual_tourists"] = tourism_filtered["annual_tourists"].apply(convert_tourists)

In [ ]:
#Convert the columns to numeric to be able to group and calculate the mean:
for col in ['annual_tourists']:
    tourism_filtered[col] = pd.to_numeric(tourism_filtered[col], errors='coerce')

In [ ]:
#Select the columns that we will need for analysis:
tourism_filtered = tourism_filtered[['city_id', 'city', 'annual_tourists', 'cost_of_living']]
tourism_filtered

    city_id      city  annual_tourists cost_of_living
0        85      Rome         14000000    Medium-high
1        31  Florence         10000000    Medium-high
2        99    Venice         10000000    Medium-high
3        64     Milan          7000000           High
4        71    Naples          5000000         Medium
..      ...       ...              ...            ...
89        3  Akureyri              200         Medium
90       10  Belgrade          1500000         Medium
91       74  Novi Sad              500         Medium
92       73       Niš              300         Medium
93       94  Subotica               20         Medium

[94 rows x 4 columns]

In [ ]:
#Re-check the data tupes:
tourism_filtered.dtypes

city_id             int64
city               object
annual_tourists     int64
cost_of_living     object
dtype: object

In [ ]:
tourism_filtered

    city_id      city  annual_tourists cost_of_living
0        85      Rome         14000000    Medium-high
1        31  Florence         10000000    Medium-high
2        99    Venice         10000000    Medium-high
3        64     Milan          7000000           High
4        71    Naples          5000000         Medium
..      ...       ...              ...            ...
89        3  Akureyri              200         Medium
90       10  Belgrade          1500000         Medium
91       74  Novi Sad              500         Medium
92       73       Niš              300         Medium
93       94  Subotica               20         Medium

[94 rows x 4 columns]

In [ ]:
tourism_filtered.loc[tourism_filtered["city"] == "Rome", ["city_id", "city"]]

   city_id  city
0       85  Rome

#### Cleaning the "Restaurants" dataset

In [ ]:
restaurants_df.head()

,Unnamed: 0,Name,City,Cuisine Style,Ranking,Rating,Price Range,Number of Reviews,Reviews,URL_TA,ID_TA
0,0,Martine of Martine's Table,Amsterdam,"['French', 'Dutch', 'European']",1.0,5.0,$$ - $$$,136.0,"[['Just like home', 'A Warm Welcome to Wintry ...",/Restaurant_Review-g188590-d11752080-Reviews-M...,d11752080
1,1,De Silveren Spiegel,Amsterdam,"['Dutch', 'European', 'Vegetarian Friendly', '...",2.0,4.5,$$$$,812.0,"[['Great food and staff', 'just perfect'], ['0...",/Restaurant_Review-g188590-d693419-Reviews-De_...,d693419
2,2,La Rive,Amsterdam,"['Mediterranean', 'French', 'International', '...",3.0,4.5,$$$$,567.0,"[['Satisfaction', 'Delicious old school restau...",/Restaurant_Review-g188590-d696959-Reviews-La_...,d696959
3,3,Vinkeles,Amsterdam,"['French', 'European', 'International', 'Conte...",4.0,5.0,$$$$,564.0,"[['True five star dinner', 'A superb evening o...",/Restaurant_Review-g188590-d1239229-Reviews-Vi...,d1239229
4,4,Librije's Zusje Amsterdam,Amsterdam,"['Dutch', 'European', 'International', 'Vegeta...",5.0,4.5,$$$$,316.0,"[['Best meal.... EVER', 'super food experience...",/Restaurant_Review-g188590-d6864170-Reviews-Li...,d6864170

In [ ]:
#Check the unique cities
restaurants_df['City'].nunique()

31

In [ ]:
#Check the data in dataframe:
restaurants_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125527 entries, 0 to 125526
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         125527 non-null  int64
 1   Name               125527 non-null  object
 2   City               125527 non-null  object
 3   Cuisine Style      94176 non-null   object
 4   Ranking            115876 non-null  float64
 5   Rating             115897 non-null  float64
 6   Price Range        77672 non-null   object
 7   Number of Reviews  108183 non-null  float64
 8   Reviews            115911 non-null  object
 9   URL_TA             125527 non-null  object
 10  ID_TA              125527 non-null  object
dtypes: float64(3), int64(1), object(7)
memory usage: 10.5+ MB

In [ ]:
#Replace the spaces with "_" in column names:
restaurants_df.columns = restaurants_df.columns.str.lower().str.replace(" ", "_")

In [ ]:
#Check the applied changes in column names:
restaurants_df.head(3)

,unnamed:_0,name,city,cuisine_style,ranking,rating,price_range,number_of_reviews,reviews,url_ta,id_ta
0,0,Martine of Martine's Table,Amsterdam,"['French', 'Dutch', 'European']",1.0,5.0,$$ - $$$,136.0,"[['Just like home', 'A Warm Welcome to Wintry ...",/Restaurant_Review-g188590-d11752080-Reviews-M...,d11752080
1,1,De Silveren Spiegel,Amsterdam,"['Dutch', 'European', 'Vegetarian Friendly', '...",2.0,4.5,$$$$,812.0,"[['Great food and staff', 'just perfect'], ['0...",/Restaurant_Review-g188590-d693419-Reviews-De_...,d693419
2,2,La Rive,Amsterdam,"['Mediterranean', 'French', 'International', '...",3.0,4.5,$$$$,567.0,"[['Satisfaction', 'Delicious old school restau...",/Restaurant_Review-g188590-d696959-Reviews-La_...,d696959

In [ ]:
#Check the unique values in "price_range" column:
restaurants_df["price_range"].unique()

array(['$$ - $$$', '$$$$', '$', nan], dtype=object)

In [ ]:
#Create a dictionary to replace the price_rnge with exploatable data
price_dict = {'$$ - $$$':'2.5', '$$$$': '4', '$':'1'}

#Replace the price_range with the values from dictionary
restaurants_df['price_range'] = restaurants_df['price_range'].replace(price_dict)

In [ ]:
#Convert the columns to numeric to be able to group and calculate the mean:
for col in ['rating', 'number_of_reviews', 'price_range']:
    restaurants_df[col] = pd.to_numeric(restaurants_df[col], errors='coerce')

In [ ]:
#Check the null or missing values:
restaurants_df.isna().sum()

unnamed:_0               0
name                     0
city                     0
cuisine_style        31351
ranking               9651
rating                9630
price_range          47855
number_of_reviews    17344
reviews               9616
url_ta                   0
id_ta                    0
dtype: int64

In [ ]:
#Check the datatypes of each column:
restaurants_df.dtypes

unnamed:_0             int64
name                  object
city                  object
cuisine_style         object
ranking              float64
rating               float64
price_range          float64
number_of_reviews    float64
reviews               object
url_ta                object
id_ta                 object
dtype: object

In [ ]:
#Functions to fill the missing data for numeric and categorical columns:
numerical_cols = ["ranking", "rating", "price_range", "number_of_reviews"]
categorical_cols = ["city"]

def fill_missing_values(restaurants_df):

    existing_numerical = [col for col in numerical_cols if col in restaurants_df.columns]
    existing_categorical = [col for col in categorical_cols if col in restaurants_df.columns]

    if existing_numerical:
        restaurants_df.loc[:, existing_numerical] = restaurants_df[existing_numerical].fillna(
            restaurants_df[existing_numerical].mean().round(2)
        )

    if existing_categorical:
        restaurants_df.loc[:, existing_categorical] = restaurants_df[existing_categorical].fillna("Unknown")

    return restaurants_df

restaurants_df = fill_missing_values(restaurants_df)

In [ ]:
#Add a new column "city_id":
restaurants_df["city_id"] = restaurants_df["city"].map(city_dict)

In [ ]:
#Reset the index and store it as a new column called 'name_id'
restaurants_df = restaurants_df.reset_index().rename(columns={'index': 'name_id'})

#Select only the columns that will be used for the analysis:
restaurants_df = restaurants_df[["name_id", "name", "city_id", "city", "ranking", "rating", "price_range", "number_of_reviews"]]
restaurants_df

,name_id,name,city_id,city,ranking,rating,price_range,number_of_reviews
0,0,Martine of Martine's Table,4,Amsterdam,1.00,5.00,2.50,136.00
1,1,De Silveren Spiegel,4,Amsterdam,2.00,4.50,4.00,812.00
2,2,La Rive,4,Amsterdam,3.00,4.50,4.00,567.00
3,3,Vinkeles,4,Amsterdam,4.00,5.00,4.00,564.00
4,4,Librije's Zusje Amsterdam,4,Amsterdam,5.00,4.50,4.00,316.00
...,...,...,...,...,...,...,...,...
125522,125522,Konrad Kaffee- & Cocktailbar,105,Zurich,3657.46,3.99,2.22,125.18
125523,125523,Blueberry American Bakery,105,Zurich,3657.46,3.99,2.22,125.18
125524,125524,Restaurant Bahnhof,105,Zurich,3657.46,3.99,2.22,125.18
125525,125525,Yoyo Pizza,105,Zurich,3657.46,3.99,2.22,125.18
125526,125526,dieci,105,Zurich,3657.46,3.99,2.50,125.18

In [ ]:
restaurants_df.loc[restaurants_df["city"] == "Rome", ["city_id", "city"]]

        city_id  city
109130       85  Rome
109131       85  Rome
109132       85  Rome
109133       85  Rome
109134       85  Rome
...         ...   ...
115074       85  Rome
115075       85  Rome
115076       85  Rome
115077       85  Rome
115078       85  Rome

[5949 rows x 2 columns]

In [ ]:
#Save the ds to .csv:
restaurants_df.to_csv('restaurants.csv', index=False)

In [ ]:
#### Create a 3rd dataset containing the "city_id" and the "city name"

In [ ]:
#Convert dictionary to DataFrame
city_df = pd.DataFrame(list(city_dict.items()), columns=['city_id', 'city'])

#Display first few rows
city_df.head()

     city_id  city
0    Aalborg     1
1     Aarhus     2
2   Akureyri     3
3  Amsterdam     4
4    Antalya     5

In [ ]:
# Inverse the order of the columns:
# Inverser les colonnes
city_df = city_df[['city_id', 'city']]
city_df.head()

     city_id  city
0    Aalborg     1
1     Aarhus     2
2   Akureyri     3
3  Amsterdam     4
4    Antalya     5

In [ ]:
#Save the ds to .csv:
city_df.to_csv('cities.csv', index=False)

#### Aggregation od data and analysis in Python:

In [ ]:
#Aggregate the data for "rating", "number_of_reviews", "price_range" and calculate the average:
restaurants_summary = restaurants_df.groupby('city_id').agg({
    'rating': 'mean',
    'number_of_reviews': 'sum',
    'price_range': 'mean'
}).reset_index()

In [ ]:
#Round numeric columns:
restaurants_summary[['rating', 'price_range']] = restaurants_summary[['rating', 'price_range']].round(2)

In [ ]:
#Merge 2 datasets in one table
new_df = pd.merge(tourism_filtered, restaurants_summary, on="city_id", how="inner")
print(new_df.shape)
new_df.head(30)

(20, 7)

,city_id,city,annual_tourists,cost_of_living,rating,number_of_reviews,price_range
0,85,Rome,14000000,Medium-high,4.23,1717509.94,2.13
1,64,Milan,7000000,High,3.82,1096638.28,2.16
2,9,Barcelona,12700000,Medium-high,3.97,1165881.98,2.19
3,59,Madrid,7000000,Medium-high,3.81,974377.98,2.25
4,80,Paris,37500000,High,3.95,1736989.92,2.29
5,58,Lyon,2000000,Medium-high,3.93,273596.04,2.28
6,101,Vienna,7500000,Medium-high,4.06,336554.34,2.27
7,19,Brussels,10000000,Medium-high,3.90,310599.88,2.28
8,25,Copenhagen,10000000,High,3.99,220935.24,2.28
9,12,Berlin,13500000,Medium-high,4.11,566917.04,2.15
10,67,Munich,10000000,Medium-high,4.02,272354.00,2.30
11,38,Hamburg,5000000,Medium-high,4.03,198122.30,2.25
12,7,Athens,10000000,Medium-high,4.19,203863.10,2.10
13,50,Lisbon,3500000,Medium-high,4.05,520373.60,2.15
14,78,Oslo,2500000,High,3.90,116656.02,2.32
15,92,Stockholm,2500000,Medium-high,3.88,214876.02,2.31
16,105,Zurich,3000000,High,4.02,135080.14,2.41
17,33,Geneva,2000000,High,3.97,122818.96,2.43
18,53,London,25000000,High,3.95,2494485.80,2.21
19,29,Edinburgh,3000000,Medium-high,4.05,422073.80,2.14

In [ ]:
#Save the ds to .csv:
new_df.to_csv('new_df.csv', index=False)